export * from "./Hero";
export * from "./Home";
export * from "./Company";
export * from "./About";
export * from "./Projects";
export * from "./Services";
export * from "./Skills";
export * from "./Reviews";
export * from "./Contact";
